# Generated by Django 5.2.4 on 2025-09-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.FloatField(null=True),
        ),
    ]
